services:
  paltalabs-reflector-challenge:
    image: esteblock/soroban-preview:22.0.1@sha256:8cc9cffca10b64e3e9b528a9ebb8ed8c154df5f39c835eb804e81edb8206593e
    container_name: paltalabs-reflector-challenge
    volumes:
      - .:/workspace
    ipc: host
    command: tail -f /dev/null
    ports:
      - "3000:3000"
      - "3010:3010"
      - "3050:3050"

networks:
  reflector-challenge-network:
    driver: bridge
